version: '3.8'
services:
  fe-app:
    image: crpi-kqvk1j9epq5u5zgd.cn-beijing.personal.cr.aliyuncs.com/ankuixing_test_namespace/ankuixing:v1
    # image: fe-container:first
    platform: linux/arm64/v8
    ports:
      - 80:80
    depends_on:
      - nest-app
    networks:
      - common-network
  nest-app:
    build:
      context: ./
      dockerfile: ./Dockerfile
    depends_on:
      - mysql-container
      - redis-container
    # ports:
    #   - 3000:3000
    networks:
      - common-network
    env_file:
      - ./src/.env
  mysql-container:
    image: mysql:localpin
    volumes:
      - /Users/ankuixing/mysql:/var/lib/mysql
    environment:
      MYSQL_DATABASE: meeting_room_booking_system
      MYSQL_ROOT_PASSWORD: akx
    networks:
      - common-network
  redis-container:
    image: redis:localpin
    volumes:
      - /Users/ankuixing/redis:/data
    networks:
      - common-network
networks:
  common-network:
    driver: bridge